swissfintechinnovations/ca-mortgage

- mortgageAPI.yaml
For IAZI-estimations, the luxus flag is in "propertyObject" needed. Name: luxusFlag
Description: If the property is luxury
not required field
String, enum: [0, 0.5, 1.0]
0 = Nein
0.5 = Teilweise
1.0 = Ja
-> Zeile 1936-1940
> New Field: Luxus Flag

- mortgageAPI.yaml
Wüest Dimensions differentiates not just renovation: true/false. Wüest Dimensions has different refurbishment Component Types: total, interior_fittings_kitchen, interior_fittings_bathroom_sanitary, interior_fittings_floor_cover, interior_fittings_remaining building_envelope_pitched_roof, building_envelope_flat_roof, building_services_heat_production, building_services_heat_emission, buildings_services_electrical_ventilation_elevator, work_on_surroundings, supporting_structure, building_envelope_windows, building_envelope_facade_balcony
renovation should therefore be built as an own object with a list/array:
refurbishmentComponentType (string, enum: see above)
yearOfRenovation (similar to "renovationYear, but different name due to no duplicated fields)
renovationCost (see your Standard for …
> New Setup: Property Renovation

- mortgageAPI.yaml
Besides the current enum (none, minergie, minergie-p, minergie-eco, minergie-p-eco) IAZI now works with two additional minergieStandardTypes:
minergie-a
minergie-a-eco
We should accept this two new types in our enum in the field "minergieStandardType".
-> Teil von Zeile 1933
> New Enum in Minergie Standard Type

- mortgageAPI.yaml
We miss a field in "Property Objects":
field name: propertyType
description: The type of property
not required
string
enum: [single_family_house, condominium, vacation_house, vacation_condominium, agricultural_farm, 2or3_family_house, multi_family_house, residential_building_plot, building_plot_other, mixed_property, commercial_condominium, office_building, industrial_building, special_object]
> New Field: Property Type

- mortgageAPI.yaml
We miss a field in "Property Objects":
field name: usageType
description: The type of usage of the financing property: self, let
not required
string
enum: [self, let]
> New Field: Usage Type

- mortgageAPI.yaml
For Wüest Dimensions estimations, we miss a field in "Property Objects":
field name: heatProduction
description: Type of the heat production
not required
array
string
enum: [oil, gas, wood, electric, geothermal_probe, district, solar_panel, solar_thermal_collector]
> New Field: Heat Production

- mortgageAPI.yaml
For Wüest Dimensions, we miss a field in "Property Objects":
field name: numberOfRoomsInGrannyFlat
description: The number of the rooms in the granny flat
not required
number, double
> New Field: Number Of Rooms In Granny Flat

- mortgageAPI.yaml
For the property estimation service (Wüest Dimensions and IAZ), we miss a field in "Property Building Information" (for single family houses):
field name: environmentStandard
description: The rating type
not required
string
enum: [high-level, basic, low-level]
> New Field: Environment Standard

- mortgageAPI.yaml
In the Field "otherFeatures" in the Object "Property Building Information" for e.g. single family house some enum are missing for Wüest Dimensions. Could we please add the following enum: indoor_pool, outdoor_pool, whirlpool_sauna, heated_conservatory, unheated_conservatory, security_system, chimney, passenger_elevator, freight_elevator
> New Enum in Other Features in Property Building Information

- mortgageAPI.yaml
In the field "otherFeatures" in the object "propertyBuildingInformation" and in the object "propertyFlatInformation", there is a grammar mistake in the enum ventilation_system_without_mingergie.
Added new enum: ventilation_system_without_minergie
> New enum: Grammar mistake in Other Features

- mortgageAPI.yaml
You know the field "objectPrice". In my view, this is the "Kaufpreis". Besides the "Kaufpreis" more types of amounts are relevant for an application. Can we add the following amounts after "object Price":
renovationAmount
description: Amount needed to pay the planned renovation (Renovationsbetrag) Type: see "Amount"
investmentCost
description: Total amount needed to pay object price and planned renovation (Total Anlagekosten) Type: see "Amount"
collateralValue
description: Value of the property as base for the securization applying the lowest value principle (Belehnungsbasis) Type: see "Amount"
limitForLandEncumbrances
description: The limit for land encumbrance according to Bundesgericht über das bäuerliche Bodenrecht, SR 211.412.11 (Belastungsgrenze BGBB)
Type: see "Amount"
> New Fields besides Object Price

- mortgageAPI.yaml
In the object "Estimation" you have the following fields:
estimationSourceType
amount
estimationDate
Estimation tools like WuP and IAZI know several "amounts". Therefore the field "Amount" is not meaningful. I suggest to rather call this field "marketValue".
Step 1 in next Release: description added.
Step 2 in Release V3.0: renaming of amount to "marketValue"
> Renaming Estimation Amount

- mortgageAPI.yaml
In the object "Estimation" I would like to add more fields to this object:
statisticalPriceRangeMax
description: Estimated statistical price range maximum type: see Amount
statisticalPriceRangeMin
description: Estimated statistical price range minimum type: see Amount
yearlyRentalIncome
description: Estimated rental income per year
type: see Amount
> New Fields: Different Amounts in Estimation

- mortgageAPI.yaml
To connect the done estimation in the core banking system with the estimation of the tpp in the external estimation tool, it would be useful if we can transfer the estimationId as a unique key.
Therefore I would like to add the following field in the object "Estimation":
name: estimationId
description: ID of the property estimation
Type: string, pattern: '^[a-zA-Z0-9]{6,10}$'
> New Field: Estimation ID

- mortgageAPI.yaml
We need a field which transfer us the date, when the pricing for the offer has been done:
Name: "datePriceFixing" or "offerValidFrom"
description: "The date when the price has been fixed" OR "The date when the offer has been made" Type: see Date
Can we add this field after the object "interest"?
changes in same lines in #73
> New Field: Date Price Fixing

- mortgageAPI.yaml
In our communication between TPP and FI, we use the TPP Applicant ID to refer to the client and we connect the dots of the different application using this key.
Therefore we would like to add to following new field in the Object "Party": Name: tppPrimaryApplicantID
Description: ApplicantId for the applying party defined by TPP Type: string, pattern: '^[a-zA-Z0-9]{6,10}$'
For the same reason, we need a new field in the Object "Applicant":
Name: tppApplicantID
Description: ApplicantId defined by TPP
Type: string, pattern: '^[a-zA-Z0-9]{6,10}$'
> New Fields: TPP Applicant IDs

- mortgageAPI.yaml
In our software we know two different channels, on which an application can be entered. The channel might have an influence on the price or on which client advisor is relevant for this application.
For this reason, we would like to have a new field in the object "application": Name: channelType
Description: The type of the channel the application was generated string
enum: [advisor, direct]
"advisor" could also be replaced by "broker"
> New Field: Channel Type

- mortgageAPI.yaml
In addition to the enum "buy" and "replacement" we consider "Baufinanzierung" as well as a mortgage type.
In "mortgageType", we would like to extend the enum by "construction_financing".
> New Enum in Mortgage Type

- mortgageAPI.yaml
In our service, different Third Party Provider can apply for a mortgage. This is why we want to extend the object "tppAdvisorDetail" with a new field:
Name: nameTpp
Description: Firm of the TPP
Type: string, max 70
> New Field: Name TPP

- mortgageAPI.yaml
For the FI it makes a difference in the affordability calculation if the applicant is renter or home_owner. depending on that the bank needs to consider other costs.
Therefore, we would like to have a new field in the object "Financial Situation":
name: residentialSituation
Type: string, enum: [home_owner, renter]
> New Field: Residential Situation

- mortgageAPI.yaml
An applicant of a mortgage can bring unpledged building plot as part of his assets (Eigenmittel). This enum is missing in the assetType.
Please add the enum: unpledged_building_plot
> New Enum in Asset Type

- mortgageAPI.yaml
For insurances (Asset Typ enum: life_insurance_3a, life_insurance_3b) two different types of amount are interesting for the FI:
surrender value / Rückkaufswert
insurance sum / Versicherungssumme
Both of them will be entered in the core banking system. So we would like to transfer both amounts. Is it possible to add a new field in the object "Asset": name: insurance sum
description: The amount of the sum insured
Type: see Amount
So, we can send the surrender value in the current field "amount" and send the insurance sum in the new field.
> New Setup: Amount for Asset Type Insurances

- mortgageAPI.yaml
Some options are missing in the enum of the "income Types": leasing_payment, consumer_loan_payment, child_allowance_payment, rental_costs, costs_for_additional_properties
Please add these to the enum.
> New Enum in Income Types

- mortgageAPI.yaml
IAZI and WüestDimensions use different estimation approaches in respect of volume in connection with garages.
both: volume of internal garages is automatically taken into account in the volume -> no issue IAZI: volume of external garages and garage boxes need to be added on the normal volume (standard volume: 60m3 each) WuP: amount of external garages and garage boxes are transfered as own fields and should not be transfered in the normal volume Therefore, we need to have two different fields for volume:
name: volumeIncludingGarageInhouse (change in naming of the current field «volumeIncludingGarage», relevant for WuP) description: The volume of the house including the inhouse garage (relevant for WuP). type: integer
example 1500
volumeIncludingAllGarages (new field, relevant for IAZI) …
> New Setup: Volume in propertyBuildingInformation

- mortgageAPI.yaml
Change details for commonErrorResponse from string to array [string].
At the moment for every error response only ONE string with details can be returned. As originally suggested by lars and oleg, we change the type to array [string].
Scope: rls3
> Change details for commonErrorResponse

- mortgageAPI.yaml
In the object "Estimation" you have the following fields:
estimationSourceType
amount
estimationDate
Estimation tools like WuP and IAZI know several "amounts". Therefore the field "Amount" is not meaningful. I suggest to rather call this field "marketValue".
Step 1 in next Release: description added : "Estimated Market value of the property" Step 2 in Release V3.0: renaming of amount to "marketValue"
So --> renaming of "amount" to "marketValue"
> Renaming Estimation Amount in Release V3.0

- mortgageAPI.yaml
In "Asset" the fields "assetType" and "amount" are required. in "liabilites" and "income", these two fields are not required. How come? We should mark these two fields in "liabilities" and "income" as required, too.
There is one more difference: asset has an additional field "assetProvider". Do we need/want this field for "liability" and "income" as well?
Anyway, why is there a different specification format for "liabilities" and "income" than for "asset"? "asset" is separately specified under "mortgage date types" whereas the other two are specified in the normal structure. Do we want to change it?
-> In this Pull request, only 1st point is addressed.
> Required Fields in Liabilities and Income

- mortgageAPI.yaml
In the field "otherFeatures" in the object "propertyBuildingInformation" and in the object "propertyFlatInformation", there is a grammar mistake in the enum ventilation_system_without_mingergie.
Could we correct that at both places?
I have added the new enum: ventilation_system_without_minergie -> for next release
we should delete enum: ventilation_system_without_mingergie in release V3.0
So --> deleted "..mingergie.." at two places
> Grammar mistake in Other Features in V3.0

- mortgageAPI.yaml
- Fixed: estimationId should be part of the estimation object
- Fixed: volumeIncludingGarage should have been deleted in Rls 3.0.0 (PR#103)
> Fix Rls 3.0.0

- mortgageAPI.yaml
We need the data fields with connection to amortization not only in the object "financingTranche" but also on a more aggregate level in the object "financing". Reason: Not always the amortization is already fixed on a tranche level. Sometimes the amortization is aggred on a total mortgage level.
After this change, we have amortization at three different places: financing, financingtranche and mortgageproductcondition. According to the new style guideline, using references is recommended. So, we want to clean up the amortization documentation.
> Amortizations as an own object

- mortgageAPI.yaml
How do you handle/transfer data in the mortgage type replacement when the credit limit should be increased?
We would like to transfer:
amount of increase
purpose of increase
withdrawn pension fund in past (question of handling in any case, also without credit increase) We would recommend to add new fields:
amount of increase in our TKB-Object "Financing" after the field "amount" and in the use case "financingRequest" after the field "amount" -> "increaseAmount" purpose of increase just after "increaseAmount" in both objects ->"increasePurpose" transfer the amount of withdrawn pension fund in past in the UsedAssets with normal meccano (because UsedAssets is not used in the mortgagetype "Replacement", right?)
> Replacement including credit increase

- mortgageAPI.yaml
For each applicant, in the field "matrimonialPropertyScheme" in the object "applicantDetail", we can send information how the property is owned: jointEstate
separateEstate
contributionToJointAcquiredProperty
In Case, the mortgage is for two debtor, but the property is owned by only Debtor A of these two debtor: What do you send in this field for Debtor A? --> I would say "separateEstate" What do you send in this field for Debtor B? --> There is no enum for this. Do you send it empty?
I would suggest to add a new enum: "none" or "n-a". So that we can send a clear message to the FI.
> New Enum in Matrimonial Property Scheme - Rel 3.x

- README.md
> Add SwaggerEditor link to Readme

- mortgageAPI.yaml
* add line breaks according to yaml linting rules
> Adjust descriptions
