swissfintechinnovations/ca-mortgage

mortgageAPI.yaml

For Wüest Dimensions, we miss a field in "Property Objects":
field name: floorPlan
description: The efficiency of the floor plan
not required
string
enum: [efficient, average, inefficient]

New Field: Floor Plan

---

mortgageAPI.yaml

What is meant with the field "increment"? Is it "Totalbetrag der Amortisation über gesamte Laufzeit"?
We need more detailled information about increment. Could we please add the following fields after "increment"?
incrementType
description: The type of increment
type: string, enum: [direct, indirect]
incrementAmount
description: The amount of the periodic increment
type: see Amount
incrementStart
description: Start date of increment
type: see date
incrementPeriodicity
description: The periodicity the increment is paid type: string, enum [yearly, quarterly, monthly]
incrementAccountNr
description: the account number from which the increment is paid
type: string

New Setup: Increment

---

mortgageAPI.yaml

We have information about the replaced tranche which we would like to send to the FI. Therefore we need the following object:
"replaced tranches" with an array of all tranches. A replaced tranche consists of 3 fields:
replacedTrancheAmount
description: The amount of the replaced tranche
type: see Amount
replacedTrancheExpiry
description: The expiry date of the replaced tranche type: see Date
replacedTrancheIssuer
description: The institute who has issued the replaced tranche
type: string
example: Credit Suisse

New Setup: Replaced Tranche

---

mortgageAPI.yaml

Our service transfers data on the rating/solvency (CRIF Score) to the FI. We would like to have relevant fields in the object "Applicant":
rating
description Solvency rating of the applicant
type: integer
ratingDate
description: Date of the solvency rating
type: see Date

New Fields: Applicant Rating

---

mortgageAPI.yaml

Besides email of the applicant, the FI needs to know a phone number. So, we want to add a new field in the applicant Detail:
Name: phone
Description: Phone Number of the applicant
Type: string

New Field: Phone in Applicant Detail

---

mortgageAPI.yaml

fix wrong description key word & double enum statement

fix description key word & double enum statement

---

mortgageAPI.yaml

Missing ":" estimationId

---

mortgageAPI.yaml

The income and costs of other properties held by the applicant need to be considered in the affordability calculation. So, the FI needs to know the situation of additional properties.
In the object "financialSituation" we would like to have a new object "additionalProperties" as a list/array: description: Information about additional property required fields: valueAdditionalProperty, propertyTypeAdditionalProperty
In the new object "additionalProperties" are the following fields:
streetNameAdditionalProperty
description: Street name of the additional property type: String, max. 70
valueAdditionalProperty
description Value of the additional property
type: see Amount
propertyTypeAdditionalProperty
description: The type of the additional property
type: string, enum: [single_family_house, …

New Setup: Additional Properties

---

mortgageAPI.yaml

Do we need to change Code Line 165 onwards, 229 onwards, too?

Inconsistency in Duration

---

mortgageAPI.yaml

Add standard response with ID for successfull post requests.
As suggested early 2022 by Lars and Oleg: Add standardadized 201 response with ID of the created resource. 
Scope: Rls 3.0

Add standard response 201

---

mortgageAPI.yaml

How do you differentiate between asset and used asset?
Answer:
if the applicant has cash CHF 200'000 and thereof he uses CHF 150'000 for financing the property as "Eigenmittel".
do you enter
CHF 200'000 in the "assets" in "financialSituation" as "assetType" cash
and CHF 150'000 in the "usedAsset" in "FinancingRequest" as "assetType" cash and "assetUsageType" withdraw?
Proposed description in "assets" in the object "financial Situation":
'Array of all assets the applicant possesses, incl. the assets which will be used for the financial request.'
Proposed description in "usedAssets" in the object "Financing Request":
'Array of all assets which will be used for the financial request. At least, all of these used assets must also be recorded in the array of assets in the financial situation of …

Assets and UsedAssets

---

mortgageAPI.yaml

What is meant with the field "increment"? Is it "Totalbetrag der Amortisation über gesamte Laufzeit"?
I would rather suggest to call it amortization. Besides this Issue we developped a more precise setup for amortization in issue #23

Renaming increment in V3.0

---

mortgageAPI.yaml

See https://github.com/swissfintechinnovations/ca-mortgage/issues/49

New Endpoint for full data transfer

---

mortgageAPI.yaml

1. Added the "reason" field to the request body for DELETE /application/{applicationId}. 
2. Added requestOfferType to the FinancingRequest model.
3. Removed "validateOnly" as it doesn't make sense.

Additional step for getting binding offers

---

mortgageAPI.yaml

add parameter & header references, update descriptions

Add references

---

.github/CODEOWNERS
LICENSE
README.md

- readme
- license
- codeowner

orga improvements

---

mortgageAPI.yaml

Fix sematic errors from SwaggerUI

---

mortgageAPI.yaml

new enums for Wuest (heatProduction)

new enums for Wuest

---

.github/workflows/lint.yaml
.github/workflows/release.yaml

change actions/checkout@v3 to actions/checkout@v4

upgrade actions/checkout

---

.github/workflows/release.yaml

grant stream leads permission to run release action

change release workflow permissions
